const countries = [
  {
    name: "San Francisco",
    left: 138,
    top: 480,
    connections: ["Chicago", "Los Angeles", "Manila", "Tokyo"],
    color: "blue",
  },
  {
    name: "Chicago",
    left: 223,
    top: 442,
    connections: ["San Francisco", "Atlanta", "Mexico City", "Montreal"],
    color: "blue",
  },
  {
    name: "Montreal",
    left: 315,
    top: 442,
    connections: ["New York", "Washington", "Chicago"],
    color: "blue",
  },
  {
    name: "New York",
    left: 364,
    top: 447,
    connections: ["London", "Madrid", "Montreal", "Washington"],
    color: "blue",
  },
  {
    name: "Washington",
    left: 347,
    top: 489,
    connections: ["New York", "Montreal", "Atlanta"],
    color: "blue",
  },
  {
    name: "Atlanta",
    left: 270,
    top: 490,
    connections: ["Washington", "Chicago", "Miami"],
    color: "blue",
  },
  {
    name: "Madrid",
    left: 507,
    top: 480,
    connections: ["Sao Paulo", "New York", "London", "Paris", "Algiers"],
    color: "blue",
  },
  {
    name: "London",
    left: 507,
    top: 428,
    connections: ["Madrid", "New York", "Essen", "Paris"],
    color: "blue",
  },
  {
    name: "Paris",
    left: 568,
    top: 450,
    connections: ["Madrid", "London", "Essen", "Milan", "Algiers"],
    color: "blue",
  },
  {
    name: "Essen",
    left: 583,
    top: 408,
    connections: ["London", "Paris", "Milan", "St. Petersburg"],
    color: "blue",
  },
  {
    name: "Milan",
    left: 610,
    top: 436,
    connections: ["Essen", "Paris", "Istanbul"],
    color: "blue",
  },
  {
    name: "St. Petersburg",
    left: 652,
    top: 384,
    connections: ["Moscow", "Essen", "Istanbul"],
    color: "blue",
  },
  {
    name: "Los Angeles",
    left: 144,
    top: 542,
    connections: ["San Francisco", "Chicago", "Mexico", "Sydney"],
    color: "yellow",
  },

  {
    name: "Mexico City",
    left: 222,
    top: 562,
    connections: ["Los Angeles", "Chicago", "Miami", "Bogotá"],
    color: "yellow",
  },
  {
    name: "Miami",
    left: 294,
    top: 552,
    connections: ["Mexico City", "Washington", "Atlanta", "Bogotá"],
    color: "yellow",
  },
  {
    name: "Bogotá",
    left: 297,
    top: 617,
    connections: ["Mexico City", "Miami", "Lima", "Sao Paulo"],
    color: "yellow",
  },
  {
    name: "Lima",
    left: 284,
    top: 692,
    connections: ["Mexico City", "Bogotá", "Santiago"],
    color: "yellow",
  },
  {
    name: "Santiago",
    left: 296,
    top: 785,
    connections: ["Lima"],
    color: "yellow",
  },
  {
    name: "Buenos Aires",
    left: 358,
    top: 748,
    connections: ["Bogotá", "Sao Paulo"],
    color: "yellow",
  },
  {
    name: "Sao Paulo",
    left: 407,
    top: 697,
    connections: ["Bogotá", "Madrid", "Lagos", "Buenos Aires"],
    color: "yellow",
  },
];

export default countries;
