const lines = [
  {
    name: "San Francisco - out - Tokyo",
    text: "Tokyo",
    color: "AntiqueWhite",
    begin: [150, 490],
    lineTo: [0, 470],
  },
  {
    name: "San Francisco - out - Manila",
    text: "Manila",
    color: "AntiqueWhite",
    begin: [150, 490],
    lineTo: [0, 500],
  },
  {
    name: "San Francisco - Chicago",
    color: "AntiqueWhite",
    begin: [150, 490],
    lineTo: [228, 450],
  },
  {
    name: "Chicago - Montreal",
    color: "AntiqueWhite",
    begin: [228, 450],
    lineTo: [317, 450],
  },
  {
    name: "Montreal - New York",
    color: "AntiqueWhite",
    begin: [317, 450],
    lineTo: [370, 457],
  },
  {
    name: "New York - map",
    color: "blue",
    begin: [370, 460],
    lineTo: [317, 480],
  },
  {
    name: "New York - Washington",
    color: "AntiqueWhite",
    begin: [370, 457],
    lineTo: [360, 497],
  },
  {
    name: "Washington - map",
    color: "blue",
    begin: [360, 497],
    lineTo: [310, 493],
  },
  {
    name: "Montreal - Washington",
    color: "AntiqueWhite",
    begin: [317, 450],
    lineTo: [360, 497],
  },
  {
    name: "Washington - Atlanta",
    color: "AntiqueWhite",
    begin: [360, 497],
    lineTo: [280, 497],
  },
  {
    name: "Atlanta - Chicago",
    color: "AntiqueWhite",
    begin: [280, 497],
    lineTo: [228, 450],
  },
  {
    name: "Chicago -  Los Angeles",
    color: "AntiqueWhite",
    begin: [228, 450],
    lineTo: [160, 550],
  },
  {
    name: "San Francisco -  Los Angeles",
    color: "AntiqueWhite",
    begin: [150, 490],
    lineTo: [150, 550],
  },
  {
    name: "Los Angeles - out - Manila",
    color: "AntiqueWhite",
    begin: [150, 550],
    lineTo: [0, 600],
  },
  {
    name: "Los Angeles - out - Manila",
    color: "AntiqueWhite",
    begin: [150, 550],
    lineTo: [0, 600],
  },
  {
    name: "Los Angeles - Mexico City",
    color: "AntiqueWhite",
    begin: [150, 550],
    lineTo: [230, 570],
  },
  {
    name: "Chicago - Mexico City",
    color: "AntiqueWhite",
    begin: [228, 450],
    lineTo: [230, 570],
  },
  {
    name: "Miami - Washington",
    color: "AntiqueWhite",
    begin: [310, 560],
    lineTo: [360, 497],
  },
  {
    name: "Miami - Atlanta",
    color: "AntiqueWhite",
    begin: [305, 560],
    lineTo: [280, 497],
  },
  {
    name: "Miami - map",
    color: "yellow",
    begin: [305, 560],
    lineTo: [287, 540],
  },
  {
    name: "Miami - Mexico City",
    color: "AntiqueWhite",
    begin: [305, 560],
    lineTo: [230, 570],
  },
];

export default lines;
